plugins {
    id 'java'
}

group = 'org.example'
version = 'unspecified'

repositories {
    mavenCentral()
}

dependencies {
    // 공통(global 모듈)
    implementation project(':global')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.3.2'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // JPA + MySQL
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'mysql:mysql-connector-java:8.0.33'

    // 카프카
    implementation 'org.springframework.kafka:spring-kafka'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // LocalDateTime 직렬화를 위한 모듈
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
}

test {
    useJUnitPlatform()
}