apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: tabletalk.kr.ncr.ntruss.com/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: order-config
            - secretRef:
                name: order-secret
            - secretRef:
                name: kafka-secret
          volumeMounts:
            - name: kafka-ca-cert
              mountPath: /etc/kafka/secrets
              readOnly: true
          resources:
            requests:
              cpu: 150m
              memory: 156Mi
            limits:
              cpu: 300m
              memory: 512Mi
      imagePullSecrets:
        - name: ncr-secret
      volumes:
        - name: kafka-ca-cert
          secret:
            secretName: kafka-cluster-cluster-ca-cert
  revisionHistoryLimit: 1
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: backend
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 80
      targetPort: 8081
      nodePort: 30081
  type: NodePort
